### ISSUE TITLE
git to-do's

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#28]
- [x] pull updates from **laravel_dev** branch into the **adminpage** and **UserController** branches
- [x] when laravel 5.6 comes out in February, create a new branch off of **laravel_dev** to update and get rid of any dependency vulnerabilities, then merge back into **laravel_dev** (actually, there's a new plan: see below)
- [x] pull updates from the **laravel_dev** branch into the **adminpage** and **UserController** branches again
- [x] consider either finishing the code on the **UserController** branch or deleting it
- [x] consider either finishing the code on the **tree** branch or deleting it (or renaming it??)
- [ ] merge laravel_dev into master and have everyone merge from master?

**Comment by aryam7** [comment]
Update: the dependency vulnerability is actually in our `package-lock.json`, not our `composer.lock` file. @GiselleSerate, maybe you want to run `npm install`?

**Comment by aryam7** [comment]
New plan:
We're not gonna update to Laravel 5.6 because it requires PHP 7.1.3 or higher. This might be something we want later, but until I can write a script that will automate the entire Study Cloud installation process, we're gonna hold off on updating.
However, we're still going to merge laravel_dev into master and have everybody run "composer install" so that everyone has the same version of laravel.

**Comment by aryam7** [comment]
My plan for the tree branch is to edit the URL that will return the tree data:
`/tree/data?topic={topic_id}&levels={levels}` instead of `/tree/data/topic/{topic_id}/levels/{levels}`
where `topic_id`, when not specified, defaults to 0 (which corresponds with the root of the tree) and `levels`, when not specified, defaults to infinity. If levels is 0, it will give you a JSON object with empty arrays as the values of "nodes" and "connections".
